### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [frontendmonster/oh-my-zsh-skill-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by ASafaeirad** [comment]
Thanks,
I'll add an MIT License.

**Comment by unixorn** [comment]
Thanks, either let me know when you've added the license so I can add it or just make a PR against [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) yourself.

**Comment by ASafaeirad** [comment]
It's done.
I would be grateful if you could do that, I'm busy right now.
Thanks :pray:

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/635, thanks for adding a license.
