### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by santiagozsh** [frontendmonster/oh-my-zsh-skill-theme#2]
![screenshot](https://user-images.githubusercontent.com/96670508/209144529-d88ca4f4-baa4-449a-8181-8e0fc05291f5.png)
Hello, I hope you are well, it would be great if you left some guide or installation of the icons in read.me, since on my pc I do not have the icons used in the terminal, so it looks quite ugly, in advance, Thank you very much for this terminal, I love your style!

**Comment by ASafaeirad** [comment]
Hello, you should install and utilize [nerd-fonts](https://www.nerdfonts.com/) for the proper icons, and make sure it is the font set as your terminal font. 
The font used in the screenshot is [DejaVu Sans Mono](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/DejaVuSansMono).

I'll add that to the README file. Thanks for letting me know.

**Comment by santiagozsh** [comment]
Thanks, this has helped me!
